# To create:
# conda env create --file environment.yml
# To update, recreate from scratch (due to --prune option of update not working):
# conda env create --file environment.yml --force
name: p22c-esgf-processing
channels:
  - conda-forge
  - defaults
dependencies:
  - notebook
  - cdo=2.*.*
  - matplotlib
  - xarray
  - NetCDF4
  - python-cdo=1.5.*
  - nco=5.*.*
